
services:
  exam-2024-postgres:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-exam-2024}
    volumes:
      - ./exam-2024-api-db:/var/lib/postgresql/exam-2024

  exam-2024-redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT:-6379}:6379
#    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-password}"]
    restart: unless-stopped

volumes:
  exam-2024-api-db: